"""Bundle a curated subset of benchmark instances into instances.js for the web app.

The web app needs to load instance data without CORS or filesystem access, so
we inline the JSON as a JavaScript object literal. This script picks a small,
representative subset (one per size class plus a few extras) and writes them
to stellarium/web/instances.js.

Run after the benchmark suite has been generated:
    python -m stellarium.web.build_instances
"""

from __future__ import annotations

import glob
import json
import os
from typing import Dict, List

from stellarium.puzzle.types import Instance


HERE = os.path.dirname(os.path.abspath(__file__))
INSTANCES_DIR = os.path.normpath(os.path.join(HERE, "..", "benchmark", "instances"))
OUT_PATH = os.path.join(HERE, "instances.js")

# Five instances per size class — enough variety for the "Random instance"
# button to feel non-repetitive, while keeping the JS bundle small (~250 KB).
PER_CLASS = 5


def _pick(instances: List[Instance]) -> List[Instance]:
    """Pick a representative spread across difficulty buckets when possible."""
    by_class: Dict[str, List[Instance]] = {}
    for inst in instances:
        by_class.setdefault(inst.size_class, []).append(inst)

    chosen: List[Instance] = []
    for size_class in ("XS", "S", "M", "L", "XL"):
        in_class = by_class.get(size_class, [])
        # Prefer the highest-decisions instances (more interesting search) but
        # also include some easier ones for variety.
        in_class_sorted = sorted(
            in_class,
            key=lambda i: (-(i.solver_decisions or 0), i.id),
        )
        # Take some hard, some easy.
        hard = in_class_sorted[: max(1, PER_CLASS // 2)]
        easy = in_class_sorted[-(PER_CLASS - len(hard)):]
        chosen.extend(hard + easy)
    return chosen


def main() -> None:
    paths = sorted(glob.glob(os.path.join(INSTANCES_DIR, "*.json")))
    if not paths:
        raise SystemExit(
            f"no instances found in {INSTANCES_DIR}. "
            "Run `python -m stellarium.benchmark.generate_suite` first."
        )

    instances = [Instance.load(p) for p in paths]
    chosen = _pick(instances)

    bundle = [inst.to_dict() for inst in chosen]
    body = json.dumps(bundle, indent=2)

    with open(OUT_PATH, "w") as f:
        f.write("// Auto-generated by stellarium/web/build_instances.py — do not edit.\n")
        f.write(f"window.STELLARIUM_INSTANCES = {body};\n")

    print(f"wrote {len(chosen)} instances to {OUT_PATH}")
    for inst in chosen:
        print(
            f"  {inst.id}  ({inst.size_class}, "
            f"n={len(inst.stars)}, edges={len(inst.edges)}, "
            f"decisions={inst.solver_decisions})"
        )


if __name__ == "__main__":
    main()
